content = """

# Section Y — Oracle Inventory & Receiving (Q531–Q560)

**531. How does Oracle Inventory (INV) relate to the Procure-to-Pay process?**
The P2P cycle ends in INV: after a PO is approved and a supplier ships goods, the receiving process (PO Receipt) creates an entry in `RCV_TRANSACTIONS` and simultaneously updates `MTL_ONHAND_QUANTITIES` in Inventory. Specifically: `RCV_TRANSACTIONS.TRANSACTION_TYPE = 'RECEIVE'` records the receipt; if routing is Direct Delivery, `TRANSACTION_TYPE = 'DELIVER'` also triggers an `MTL_TRANSACTIONS` record updating on-hand. If routing is Standard Receipt (two-step), the Deliver step moves goods from receiving dock to subinventory. The financial side: receipt creates a `RCV_RECEIVING_SUB_LEDGER` entry debit `Receiving Inspection / Inventory`; PO match in AP creates the credit to `AP_INVOICES_ALL`. INV is where the physical on-hand balance is maintained.

**532. What is the difference between a Receipt and a Delivery in Oracle Receiving?**
**Receipt:** recorded at the dock — goods arrive from the supplier; creates `RCV_SHIPMENT_HEADERS` and `RCV_TRANSACTIONS` with `TRANSACTION_TYPE = 'RECEIVE'`. At this point, goods are in the "receiving dock" location, not yet in inventory. **Delivery:** moves goods from receiving dock to a subinventory/locator within inventory; creates `RCV_TRANSACTIONS` with `TRANSACTION_TYPE = 'DELIVER'` and triggers an `MTL_MATERIAL_TRANSACTIONS` record updating `MTL_ONHAND_QUANTITIES`. For routing = Direct Delivery, both happen simultaneously in one step. For routing = Inspection Required: receipt → inspect (`ACCEPT`/`REJECT`) → deliver. Understanding this distinction is critical for debugging "goods received but not in inventory" issues.

**533. What is RVCTP and what does it process?**
RVCTP (Receiving Transaction Processor) is the concurrent program `RVCTP` that processes records from `RCV_TRANSACTIONS_INTERFACE` into `RCV_TRANSACTIONS`. It also handles the inventory delivery step (updating `MTL_ONHAND_QUANTITIES`). In a normal flow: iSupplier ASN submit → records inserted into `RCV_HEADERS_INTERFACE` and `RCV_TRANSACTIONS_INTERFACE` → RVCTP runs → records moved to `RCV_SHIPMENT_HEADERS` and `RCV_TRANSACTIONS`. If RVCTP is stuck or not running, ASN submissions appear "pending" forever with no error to the supplier. Diagnose by checking `FND_CONCURRENT_REQUESTS` for RVCTP status, and `RCV_TRANSACTIONS_INTERFACE.PROCESSING_STATUS_CODE` (should be `PENDING` waiting for RVCTP, `ERROR` if failed, `SUCCESS` if processed).

**534. What are the standard receiving routing options in Oracle EBS and when would you use each?**
Three routing options in `RCV_ROUTING_RULES`: (1) **Standard Receipt** — goods go to receiving dock first, then manually delivered to subinventory. Use for: high-value items needing physical inspection before stocking. (2) **Inspection Required** — receipt → inspection (Accept/Reject) → deliver. Use for: items with quality requirements, aerospace components requiring incoming inspection. GE used this for critical manufacturing parts. (3) **Direct Delivery** — receipt and delivery in one step; goods immediately posted to inventory. Use for: low-value consumables, MRO items where dock-to-inventory speed matters. Controlled at item/supplier site/receiving options level. Override via `RCV_PARAMETERS.RECEIVING_ROUTING_ID`.

**535. What is the difference between Subinventory and Locator in Oracle Inventory?**
**Subinventory:** a logical subdivision of an inventory organization (warehouse) — e.g., "FG-STORE" (Finished Goods), "RM-STORE" (Raw Materials), "QUARANTINE". Each subinventory has its own GL account codes. Items are stocked and tracked at subinventory level. **Locator:** a physical location within a subinventory — e.g., Row A, Bin 3, Shelf 2. Locators are optional and controlled by `MTL_PARAMETERS.STOCK_LOCATOR_CONTROL_CODE`. When locator control is enabled, every transaction (receipt, transfer, issue) requires specifying the exact locator. For aerospace parts at GE, locator control was enabled in the critical parts subinventory for lot traceability. Query locators: `MTL_ITEM_LOCATIONS` table.

**536. Explain Standard Delivery vs Direct Delivery for a purchase order receipt.**
Same as routing options: **Standard Receipt / Standard Delivery** is a two-step process — you first receive (creates RCV entry at dock) then separately deliver to a subinventory (creates INV transaction). **Direct Delivery** collapses both into one step at receive time — the system prompts for the destination subinventory/locator and immediately transfers on-hand. The choice impacts accounting timing: with standard, `Receiving Inspection` account is debited at receipt and cleared at delivery; with direct, inventory account is debited immediately at receipt. For financial close accuracy, many organizations prefer direct delivery for simple items to avoid timing differences between receipt and delivery.

**537. What is the Inspection Routing and how is it processed in Oracle?**
When a PO line has `INSPECTION_REQUIRED_FLAG = 'Y'` (set on item or receiving options), the receipt creates an inspection record. The quality inspector must then run `Receiving > Receiving Transactions > Inspect` to record Accept or Reject with a quantity. Accepted quantity proceeds to delivery; rejected quantity goes to `REJECT` disposition (vendor return, scrap, or rework). In Oracle tables: `RCV_TRANSACTIONS` has a record with `TRANSACTION_TYPE = 'ACCEPT'` or `'REJECT'`. The inspection step creates `QA_RESULTS` records if Oracle Quality (QA) module is integrated. For GE aerospace, incoming inspection for critical fasteners was mandatory — integrated with QA collection plans requiring dimensional measurements before acceptance.

**538. What are MTL_SUPPLY and MTL_DEMAND and how are they used?**
`MTL_SUPPLY` tracks expected future supply: open PO shipments, in-transit shipments, WIP completions, internal requisitions. Each row represents a supply source with expected receipt date and quantity. Used by MRP/ASCP for planning calculations. `MTL_DEMAND` tracks demand: sales orders, WIP requirements, internal orders. The net requirement is supply - demand. In the context of iSupplier/receiving: when a PO is approved, `MTL_SUPPLY` gets a row with `SUPPLY_TYPE_CODE = 'PO'`. When the receipt is processed by RVCTP, the supply row is reduced (or deleted if fully received). If you see a PO still showing in supply after full receipt, it means RVCTP didn't complete successfully or `QUANTITY_RECEIVED` wasn't updated properly.

**539. How do you perform a receipt correction in Oracle EBS?**
Use `Receiving > Receiving Transactions > Receiving Corrections`. Select the original receipt transaction, enter the corrected quantity (can be negative to reduce received quantity). This creates a new `RCV_TRANSACTIONS` row with `TRANSACTION_TYPE = 'CORRECT'` and the correction quantity. The correction reverses the inventory and accounting impact of the original receipt proportionally. Important: corrections have limits — you cannot correct below zero or above the original shipment quantity. For a full reversal (return to vendor), use the `RETURN TO VENDOR` transaction type instead. In iSupplier, suppliers cannot perform corrections — only internal receiving staff. A supplier who submitted a wrong ASN quantity must ask the GE receiving team to perform the correction.

**540. How do you perform a Subinventory Transfer in Oracle Inventory?**
`Inventory > Transactions > Subinventory Transfer` — enter item, from-subinventory (and locator if controlled), to-subinventory (and locator), quantity. This creates an `MTL_MATERIAL_TRANSACTIONS` record with `TRANSACTION_TYPE_ID` corresponding to "Subinventory Transfer" (typically type 2). The accounting impact: debit the receiving subinventory's valuation account, credit the sending subinventory's account. No external cost impact. In tables: `MTL_ONHAND_QUANTITIES` is updated — source subinventory quantity decreases, destination increases. Common use case: moving items from QUARANTINE subinventory to RM-STORE after quality release.

**541. What INV transaction types are commonly used in Oracle EBS?**
Key `MTL_TRANSACTION_TYPES`: (1) `RECEIVE` (type 18) — receipt from PO. (2) `DELIVER` (type 17) — delivery from receiving to subinventory. (3) `RETURN TO RECEIVING` (type 15) — return from subinventory to receiving dock. (4) `RETURN TO VENDOR` (type 10) — return from receiving to vendor. (5) `SUBINVENTORY TRANSFER` (type 2) — move between subinventories. (6) `ISSUE` (type 1) — issue to WIP or cost center. (7) `MISC RECEIPT` (type 42) — ad-hoc receipt not from PO. (8) `CYCLE COUNT ADJUSTMENT` (type 4) — inventory adjustment from cycle count. (9) `PHYSICAL INVENTORY ADJUSTMENT` (type 8) — adjustment from physical inventory count. Each type has a defined accounting template in `MTL_TRANSACTION_ACCOUNTS`.

**542. What is over-receipt tolerance and how is it enforced in Oracle EBS?**
Over-receipt tolerance defines how much more than the PO quantity a receiver can accept. Controlled by: `PO_LINE_LOCATIONS_ALL.OVER_RECEIPT_TOLERANCE` (quantity %) and `OVER_RECEIPT_ACTION` (`NONE` = allow, `WARNING` = warn but allow, `REJECT` = block). Set at PO shipment level, defaulted from receiving options. For example: tolerance = 10%, PO qty = 100, max receivable = 110. If supplier ships 115 and `OVER_RECEIPT_ACTION = 'REJECT'`, the receipt transaction is blocked with an error message. For aerospace procurement where exact quantities matter (lot traceability), GE used `REJECT` with 0% tolerance for critical parts. Tolerance is also checked in the `RVCTP` program — errors appear in `PO_INTERFACE_ERRORS` if processing via interface.

**543. Explain the columns QUANTITY_RECEIVED, QUANTITY_DELIVERED, and QUANTITY_BILLED on PO_LINE_LOCATIONS_ALL.**
- `QUANTITY_RECEIVED`: total quantity received at the dock (sum of `RCV_TRANSACTIONS` with `TRANSACTION_TYPE = 'RECEIVE'` for this shipment). Updated by RVCTP. - `QUANTITY_DELIVERED`: total quantity delivered from dock to inventory (sum of `DELIVER` transactions). For direct delivery, equals `QUANTITY_RECEIVED`. - `QUANTITY_BILLED`: total quantity matched on approved AP invoices (`AP_INVOICE_LINES_ALL` matched to this PO shipment). Used for three-way match. The relationship: `QUANTITY_ORDERED >= QUANTITY_RECEIVED >= QUANTITY_DELIVERED`. `QUANTITY_BILLED <= QUANTITY_DELIVERED` for 3-way match. If `QUANTITY_BILLED > QUANTITY_DELIVERED`, an AP match exception is raised. These columns are critical for the P2P reconciliation report.

**544. How does LOT and Serial number control work in Oracle Inventory for aerospace components?**
**Lot control** (`MTL_LOT_NUMBERS`): a batch of items sharing the same production run/supplier lot. For aerospace fasteners, every receipt must specify the supplier lot number — stored in `MTL_TRANSACTION_LOT_NUMBERS`. Lot genealogy tracks which lots were used in which assemblies. **Serial control** (`MTL_SERIAL_NUMBERS`): each unit has a unique serial number. Used for engines, landing gear assemblies. Receiving requires entering each serial number individually. **Lot + Serial:** some items (rotable parts) use both. In Oracle: `MTL_SYSTEM_ITEMS_B.LOT_CONTROL_CODE` and `SERIAL_NUMBER_CONTROL_CODE` control this. Receiving transaction for a lot-controlled item: `MTL_TRANSACTION_LOT_NUMBERS` is populated alongside `MTL_MATERIAL_TRANSACTIONS`. Traceability query: from `MTL_TRANSACTION_LOT_NUMBERS` trace `LOT_NUMBER` back to `RCV_SHIPMENT_LINES.SHIPMENT_LINE_ID` to find originating PO.

**545. How do you diagnose a stuck Receiving Transaction Interface record?**
Step 1: Query `RCV_TRANSACTIONS_INTERFACE WHERE PROCESSING_STATUS_CODE = 'ERROR'` — note `INTERFACE_TRANSACTION_ID`. Step 2: Join to `PO_INTERFACE_ERRORS ON INTERFACE_LINE_ID = INTERFACE_TRANSACTION_ID` — read `ERROR_MESSAGE`. Common errors: `PO_PDOI_VALUE_TOO_LONG` (a text value too long), `RCV_INVALID_ORGANIZATION` (ship-to org not set up), `RCV_SHIPMENT_NUM_FROZEN` (shipment already closed). Step 3: Fix the root cause — correct the data in the interface table directly (update the column with the invalid value) or fix the master data (add the organization). Step 4: Reset `PROCESSING_STATUS_CODE = 'PENDING'` and `PROCESSING_MODE_CODE = 'BATCH'` in `RCV_TRANSACTIONS_INTERFACE`. Step 5: Run `RVCTP` to reprocess. Step 6: Verify `RCV_SHIPMENT_HEADERS` and `RCV_TRANSACTIONS` are created.

**546. What is Kanban replenishment and how does it work in Oracle Inventory?**
Kanban is a pull-based replenishment system: when a Kanban card's on-hand falls to the replenishment point, a replenishment signal is automatically generated. In Oracle INV: (1) Define Kanban cards (`MTL_KANBAN_CARDS`) with `SUPPLY_STATUS = 'WAIT'` initially. (2) When a card's bin is emptied, the signal changes to `SUPPLY_STATUS = 'EMPTY'`. (3) Oracle generates a replenishment request — for supplier Kanban, this creates an `RCV_SUPPLY` record or triggers a blanket release. (4) Supplier ships, receipt is processed, card status returns to `FULL`. Used in GE's manufacturing sites for low-value, high-frequency MRO items (fasteners, consumables) — reduced purchase order processing overhead significantly.

**547. What is consigned inventory and how is it managed in Oracle EBS?**
Consigned inventory: supplier owns the goods physically stored at the customer's location; ownership transfers only upon consumption. In Oracle INV/iSupplier: (1) Supplier ships consigned stock — a "consigned receipt" in `RCV_TRANSACTIONS` with `CONSIGNED_FLAG = 'Y'`. On-hand is tracked in `MTL_ONHAND_QUANTITIES` but in a consigned subinventory. (2) When the manufacturer consumes the item (issues to WIP), Oracle generates a consumption advice. (3) The consumption advice triggers an invoice from the supplier. (4) Reporting: `PO_APOOL_DETAILS` and `PO_CONSIGNED_CONSUMPTION` views. Benefits: reduced inventory carrying costs, improved cash flow. For GE, consignment was used for fastener programs where suppliers managed replenishment levels on-site.

**548. What is Oracle WMS (Warehouse Management System) and how does it extend INV?**
Oracle WMS adds directed putaway, task dispatching, pick wave management, and RF/barcode integration to base INV. Extensions: (1) **Directed putaway** — system suggests optimal locator for receipts based on item characteristics, subinventory capacity rules. (2) **Task interleaving** — combines pick and putaway tasks for warehouse workers to minimize travel. (3) **Label printing** — automatic GS1 label generation on receipt. (4) **Mobile transactions** — RF device integration for real-time transaction recording. (5) **Lot genealogy** — enhanced tracking for aerospace. In EBS, WMS is a licensed module; its tables are in the INV schema. For GE's distribution centers, WMS directed putaway reduced mis-stocking by 30% for lot-controlled items.

**549. What are RCV_ACCOUNTING_EVENTS and when are they created?**
`RCV_ACCOUNTING_EVENTS` captures the trigger events for receiving accounting (Subledger Accounting). Created when: (1) PO receipt is processed (`RECEIVE` transaction) — creates events for Accrual and Receiving Inspection accounts. (2) Delivery to inventory — creates Inventory Valuation debit. (3) Return to Vendor — reversal entries. (4) Price correction — if PO price is corrected after receipt, accounting event created to adjust the difference. The actual journal entries are in `XLA_AE_HEADERS` and `XLA_AE_LINES` (Subledger Accounting). The link: `RCV_ACCOUNTING_EVENTS.ACCOUNTING_EVENT_ID` → `XLA_EVENTS.EVENT_ID` → `XLA_AE_HEADERS.AE_HEADER_ID`. Use this chain to debug "receipt not showing in GL" issues.

**550. Describe a complex receiving scenario from your GE Aerospace experience.**
A critical fastener batch (Lot GE-2024-001) was received against a PO with inspection-required routing. The receipt went into QUARANTINE subinventory. Quality ran dimensional checks, found 5% out-of-spec, and rejected 50 units out of 1000. The 50 units were returned to vendor (`RCV_TRANSACTIONS.TRANSACTION_TYPE = 'RETURN TO VENDOR'`); the 950 were accepted and delivered to RM-STORE subinventory at Locator A-3-12. Two weeks later, a production issue was traced to this lot — we needed to quarantine all remaining units. I wrote a SQL query joining `MTL_TRANSACTION_LOT_NUMBERS → MTL_MATERIAL_TRANSACTIONS → MTL_ONHAND_QUANTITIES` to find every bin containing Lot GE-2024-001, then created a subinventory transfer request to move them back to QUARANTINE. Report went to quality and production management within 2 hours.

**551. What is an Internal Requisition and an Internal Sales Order (ISO) in Oracle?**
An **Internal Requisition** (IR) is a request from one inventory organization to transfer goods to another organization within the same company. It flows: (1) Requesting org raises IR in `PO_REQUISITION_HEADERS_ALL` with `TYPE_LOOKUP_CODE = 'INTERNAL'`. (2) Auto-created into an Internal Sales Order (ISO) in Order Management (`OE_ORDER_HEADERS_ALL`). (3) Shipping org picks, ships, creates an `RCV_SHIPMENT_HEADERS` with `SHIPMENT_TYPE = 'INTERNAL'`. (4) Requesting org receives via standard receiving process. Distinguishing column: `RCV_SHIPMENT_HEADERS.SHIPMENT_TYPE` = 'STANDARD' for supplier receipts, 'INTERNAL' for inter-org transfers. Used at GE for transferring excess fastener stock from one manufacturing site to another without a new external PO.

**552. What are the functional steps for a Return to Vendor (RTV) transaction?**
(1) Navigate to `Receiving > Returns > Return to Supplier`. (2) Find the original receipt via PO number or receipt number. (3) Enter return quantity and reason code (e.g., 'DEFECTIVE', 'WRONG_ITEM'). (4) Select return routing: RMA if supplier requires a Return Merchandise Authorization, or standard return. (5) System creates `RCV_TRANSACTIONS` with `TRANSACTION_TYPE = 'RETURN TO VENDOR'`. (6) If goods are in inventory (delivered), a reverse `MTL_MATERIAL_TRANSACTIONS` reduces on-hand. (7) AP debit memo is created (or AP team manually handles the credit). (8) A `PO_ACCEPTANCES` record or `PO_ACTION_HISTORY` entry records the return reason. Impact on PO: `QUANTITY_RECEIVED` on `PO_LINE_LOCATIONS_ALL` is reduced by the return quantity.

**553. What happens to the accounting period in MTL_PARAMETERS during inventory close?**
`MTL_PARAMETERS.PERIOD_CLOSE_STATUS` and the `ORG_ACCT_PERIODS` table track the current and past periods. During month-end: (1) Run `Inventory > Accounting Close Cycle > Inventory Accounting Periods` — verify all pending transactions are processed (no uncosted transactions in `MTL_MATERIAL_TRANSACTIONS` with `COSTED_FLAG = 'N'`). (2) Transfer to GL (`MTL_PENDING_OSP_TRANSACTIONS` cleared). (3) Close period — sets `ORG_ACCT_PERIODS.PERIOD_CLOSE_DATE`. After close, new transactions are booked in the next open period. If a transaction is entered in a closed period, Oracle either rejects it or books it in the next open period depending on the `INV: Allow Posting in Prior Period` profile option.

**554. How does the costing method impact the receiving accounting in Oracle Inventory?**
Oracle INV supports: Standard Cost, Average Cost, FIFO, LIFO (last three in 11i/R12 with Average costing). (1) **Standard Cost**: receipts are booked at the PO's standard cost; any variance between PO price and standard goes to a `PURCHASE PRICE VARIANCE` account. Common in manufacturing. (2) **Average Cost**: receipt cost = PO unit price; running average is recalculated: `(existing qty × avg cost + receipt qty × PO price) / (existing qty + receipt qty)`. No PPV. (3) **FIFO**: cost layers maintained in `CST_INV_LAYERS` — oldest cost layers are consumed first on issues. For aerospace traceability (lot-specific costs), FIFO with lot costing provides true cost per lot. The costing method affects `RCV_RECEIVING_SUB_LEDGER` and ultimately the GL entries generated by RVCTP.

**555. What are blanket release tolerances and how do they affect receiving?**
A Blanket Purchase Agreement (BPA) has a total committed amount. Each release against the BPA consumes that commitment. Tolerances: (1) **Amount tolerance** — a release can exceed its scheduled amount by X% before a hold is placed. (2) **Quantity tolerance** — similar for quantity-based BPAs. Set at `PO_HEADERS_ALL` (BPA header) or `PO_LINE_LOCATIONS_ALL` (release shipment). At receiving: if `QUANTITY_RECEIVED > QUANTITY_ORDERED + tolerance`, `CLOSED_CODE` may be set to prevent further receipts. For GE's blanket fastener programs, we allowed 5% quantity tolerance to accommodate shipping variances. Relevant columns: `PO_LINE_LOCATIONS_ALL.OVER_RECEIPT_TOLERANCE`, `PO_HEADERS_ALL.BLANKET_TOTAL_AMOUNT`, `AMOUNT_LIMIT`.

**556. Write a SQL query to find current on-hand quantities for a specific item across all organizations.**
```sql
SELECT moq.organization_id,
       ood.organization_name,
       moq.subinventory_code,
       msib.segment1 item_number,
       msib.description,
       SUM(moq.transaction_quantity) on_hand_qty,
       msib.primary_unit_of_measure uom
FROM   mtl_onhand_quantities moq
JOIN   mtl_system_items_b msib
       ON msib.inventory_item_id = moq.inventory_item_id
       AND msib.organization_id  = moq.organization_id
JOIN   org_organization_definitions ood
       ON ood.organization_id = moq.organization_id
WHERE  msib.segment1 = :p_item_number
GROUP  BY moq.organization_id, ood.organization_name,
          moq.subinventory_code, msib.segment1,
          msib.description, msib.primary_unit_of_measure
ORDER  BY ood.organization_name, moq.subinventory_code;
```

**557. What is FIFO dating in Oracle Inventory and how does it relate to lot control?**
FIFO (First In, First Out) dating ensures that the oldest lot/receipt is consumed first during issues or picks. In Oracle WMS, FIFO putaway/picking rules use `MTL_LOT_NUMBERS.EXPIRATION_DATE` or `CREATION_DATE` to sequence lot consumption. In standard INV without WMS, FIFO isn't automatically enforced — the user must select the lot during issue. With `MTL_PARAMETERS.FIFO_COSTING = 'Y'` (Average Costing with FIFO layers), cost layers in `CST_INV_LAYERS` are consumed in creation order. For aerospace shelf-life-controlled items (e.g., adhesives, lubricants with expiry dates), FIFO is mandatory. WMS FIFO rule: `CST_INV_LAYER_COST_DETAILS` stores per-layer costs; `MTL_LOT_NUMBERS.EXPIRATION_DATE` drives picking sequence.

**558. How do you reconcile PO receipts with inventory on-hand quantities when there is a discrepancy?**
Discrepancy scenario: PO shows 1000 units received but inventory on-hand shows 950. Steps: (1) Confirm `PO_LINE_LOCATIONS_ALL.QUANTITY_RECEIVED = 1000`. (2) Check `RCV_TRANSACTIONS` — are all 1000 units in `DELIVER` transactions (not just `RECEIVE`)? Direct delivery should have both. (3) Check `MTL_MATERIAL_TRANSACTIONS` for `TRANSACTION_TYPE_ID = 17` (Deliver) against this receipt — sum should be 1000. (4) If only 950 delivered, check for a correction transaction reversing 50 units. (5) Also check `RCV_TRANSACTIONS.TRANSACTION_TYPE = 'RETURN TO VENDOR'` — were 50 returned? (6) Check `MTL_ONHAND_QUANTITIES` — are there negative adjustments (cycle count, physical inventory adjustment, issues to WIP) explaining the difference? Report findings to the warehouse manager with transaction-level detail.

**559. What INV profile options are critical for a receiving setup?**
Key profile options: (1) `RCV: Processing Mode` — ONLINE (immediate) vs BATCH (via RVCTP). For iSupplier ASN, BATCH is standard. (2) `RCV: Warn if Outside Receipt Days` — warn when receipt is outside the allowed receipt days window. (3) `INV: Lot Expiration Action` — WARN or REJECT when receiving a lot past expiry date. (4) `INV: Interorg Transfer Type` — 1=Direct, 2=Intransit; defines how inter-org transfers work. (5) `TP: INV Transfer to GL` — 'Y' means automatic transfer; 'N' means manual. (6) `INV: Allow Expense to Asset Transfer` — controls whether items in expense subinventories can be transferred to asset subinventories. (7) `PO: Warn/Enforce Receiving Date Range` — allows/blocks receipts outside the PO date window. Set these correctly during implementation to avoid hard-to-diagnose receiving errors.

**560. What is lot genealogy and why is it important for aerospace manufacturing?**
Lot genealogy traces the complete history of a lot: from supplier (origin lot, certificate of conformance) → incoming receipt (EBS lot number, receiving date, receiving transaction) → quality inspection result → subinventory location → WIP issue (which work order, which assembly) → finished goods lot. In Oracle, this is tracked via: `MTL_TRANSACTION_LOT_NUMBERS` (links lot to every transaction), `WIP_REQUIREMENT_OPERATIONS` (WIP component lots), `WIP_COMPLETED_LOTS` (finished goods lots). For aerospace, if a part is found defective in service, lot genealogy answers: which other assemblies used parts from the same supplier lot? This drives the "affected units" list for an airworthiness directive. In GE's implementation, we built a custom BIP report `XXGE_LOT_GENEALOGY_RPT` that traverses the full chain from `RCV_SHIPMENT_LINES` to final assembly, used by quality engineering within minutes of a reported defect.
"""

with open("/Users/himanshu/Desktop/Job/Job Preparation/Interview_Prep_200_QA.md", "a", encoding="utf-8") as f:
    f.write(content)

print("Section Y appended (Q531-Q560)")
