content = """

# Section Z — Tools, DevOps & Agile (Q561–Q600)

**561. How did you apply Agile/Scrum in the GE iSupplier rollout?**
We ran 2-week sprints with a backlog of user stories broken down by CEMLI (each CEMLI as an epic, subtasks for design/dev/unit test/UAT fix). Sprint ceremonies: planning (Monday AM — commit stories for the sprint), daily standups (15 min — what done, what today, blockers), sprint review (Friday — demo to functional leads in UAT), retrospective (30 min — what to improve). Velocity tracked in JIRA — story points based on complexity (1=simple config, 3=CO extension, 8=new OAF page, 13=new workflow). Releases aligned to go-live phases: Phase 1 sprint 1–6 (core PO view + ASN), Phase 2 sprint 7–10 (invoice view + promise date). Agile worked well for iterative delivery; functional leads gave feedback every 2 weeks rather than waiting until UAT.

**562. How did you use JIRA to manage the iSupplier project?**
JIRA structure: one Project (`ISUP`), Epics per CEMLI (`ISUP-E01: OAF ASN Creation`, `ISUP-E02: BIP PO Acknowledgement Report`), Stories for functional requirements, Sub-tasks for dev/test. Labels: `P1`, `P2`, `BLOCKED`, `TECH-DEBT`. Custom fields: CEMLI ID, Dev Owner, Test Script ID, Patch Risk. Workflows: `Open → In Progress → Code Review → UAT → Done` (P1 bugs get an `EMERGENCY` lane bypassing normal flow). JIRA board views: sprint board (developer view), Kanban board (bug triage), Release dashboard (UAT sign-off status). Automation rules: when Sub-task status = Done and all sibling sub-tasks Done → auto-transition parent Story to Review. Reported sprint metrics and defect trends to PM and stakeholders in weekly reports generated from JIRA dashboards.

**563. How do you use Git for managing EBS customization source code?**
Git repo structure: `ebs-customizations/` with directories: `sql/` (DDL scripts, data fix scripts), `plsql/` (package specs/bodies organized by module), `oaf/` (Java source, XML metadata), `bip/` (BIP data template XML, RTF template files), `fndload/` (FNDLOAD `.ldt` export files), `workflow/` (WF `.wft` export files), `scripts/deployment/` (deployment runbook scripts). Each CEMLI in its own sub-directory under the appropriate module. Commit message convention: `[JIRA-ID] Brief description`. Never commit: compiled JARs, binary files, credentials, `APPS_PASSWD` values. `.gitignore` excludes `*.class`, `*.jar`, `*.lox`. PRs required for merges to `develop` and `main` — at least one reviewer.

**564. What is your branching strategy for EBS development?**
Git Flow variant: `main` (PROD-ready code), `develop` (integration branch), `feature/JIRA-ID-description` (individual CEMLI dev), `hotfix/JIRA-ID-description` (emergency PROD fixes). Workflow: developer creates feature branch from `develop`; develops and unit tests locally; raises PR to `develop`; code reviewed by lead; merged to `develop`; weekly `develop` → `release/sprint-N` branch for UAT deployment; after UAT sign-off, `release/sprint-N` → `main` → tagged `v1.2.0`. Hotfixes: branch from `main`, fix, test, merge to `main` AND back-merge to `develop`. No force-pushes to `main` or `develop` — protected branches. This strategy gives us a clear history of what's in each environment at any time.

**565. How is Jenkins used in an EBS development pipeline?**
Our Jenkins pipeline had stages: (1) **Build** — compile Java/OAF source using JDeveloper headless build (`ojdeploy`); produce JAR artifact. (2) **PL/SQL deploy to DEV** — run SQL scripts via JDBC (`sqlplus` with `@` scripts); compile packages. (3) **FNDLOAD to DEV** — upload LDT files for menus, responsibilities, profile options. (4) **OAF JAR deploy to DEV** — copy JAR to `$JAVA_TOP`, restart OC4J (via `adapcctl.sh` on the app server). (5) **Smoke test** — hit a health-check URL to verify OAF startup. (6) **Notify** — Slack/email notification with build status and link to logs. Triggered by merge to `develop` branch. Manual trigger for UAT and PROD deployments (with approval gate). Jenkins ran on an internal server with SSH access to app/DB servers.

**566. What automated testing approaches work for OAF customizations?**
Full OAF UI automation is difficult due to EBS's complex session management (ICX cookies, BC4J state). Practical approaches: (1) **PL/SQL unit tests with utPLSQL** — test all business logic in packages independently of the UI. Best ROI for EBS. (2) **Oracle Application Testing Suite (OATS)** — Oracle's official tool; can record and replay OAF sessions; handles ICX session tokens automatically. Used for critical smoke tests after each deployment. (3) **Selenium with custom session management** — authenticate via EBS login, then navigate; brittle due to dynamic IDs in OAF-generated HTML. (4) **Manual test scripts** — numbered steps with expected results; executed by QA tester. Even without full automation, having utPLSQL on the PL/SQL layer catches ~60% of regressions at the logic level before any UI testing.

**567. What is an environment refresh and when is it needed?**
An environment refresh copies PROD data (or a sanitized subset) to DEV/UAT. Needed when: (1) UAT data is too stale — test data doesn't reflect current PROD configurations (responsibilities, profile options, supplier setup). (2) After a PROD patch — UAT must match PROD's patch level. (3) Preparing for a major feature regression test — needs realistic data volumes. Process: DBA takes a Data Pump export of PROD, imports to UAT (with password scrambling for security — `FND_USER.ENCRYPTED_FOUNDATION_PASSWORD` masked). Then apply any environment-specific config (DEV/UAT profile options, test users). Schedule during a weekend to minimize disruption. After refresh: verify CEMLI deployments — code deployed to UAT pre-refresh may be lost and needs redeployment.

**568. How do you manage EBS releases and coordinate deployments across DEV → UAT → PROD?**
Release management process: (1) JIRA release version (e.g., `v2.3`) tags all tickets going into the release. (2) Developer generates a deployment package: FNDLOAD scripts, SQL scripts, JAR files, deployment runbook — all in a versioned folder in Git. (3) UAT deployment: change request in ServiceNow; DBA and app team execute the runbook in UAT; functional tester validates. (4) PROD deployment: CTASK in ServiceNow with: change description, deployment steps, validation steps, rollback steps, risk assessment, approval from IT manager. Change window: Saturday 10 PM – 2 AM. (5) Post-deployment: developer validates in PROD using a smoke test script; closes CTASK with evidence. (6) Version tag applied to Git `main` branch. Release notes documented in Confluence.

**569. How does ServiceNow fit into the EBS change management process?**
ServiceNow is the IT change management system. Every PROD deployment requires a **Change Request** (CR) in ServiceNow. CR contains: change title, description, risk level (Low/Medium/High), impacted systems, deployment window, implementation steps, backout steps, approvers (dev lead, IT manager, CAB for High risk). For urgent fixes: use an **Emergency Change** type — same fields but faster approval (CAB chair approval only). **CTASKs** (change tasks) are sub-tasks within a CR for specific actions: CTASK-1 "DBA: Run DDL scripts", CTASK-2 "App team: Deploy OAF JAR", CTASK-3 "Dev: Validate smoke test". Each CTASK assignee updates their task with completion notes. The CR is closed only when all CTASKs are closed and the functional owner verifies the change. This creates an audit trail for SOX/compliance requirements.

**570. Walk through writing a CTASK for an OC4J bounce.**
CTASK Title: `CTASK-2 — Bounce OC4J on APP01 and APP02 for OAF JAR deployment`

Implementation Steps:
```
1. SSH to APP01 as oracle user
2. Stop OC4J: $ADMIN_SCRIPTS_HOME/adapcctl.sh stop
3. Wait 60 seconds for graceful shutdown
4. Verify stopped: ps -ef | grep opmn (no opmn process)
5. Copy JAR: cp /deploy/XXGE_ASN.jar $JAVA_TOP/xxge/
6. Clear OAF cache: rm -rf $OA_HTML/.cache/*
7. Start OC4J: $ADMIN_SCRIPTS_HOME/adapcctl.sh start
8. Wait 2 minutes for startup
9. Verify: tail -100 $LOG_HOME/opmn/opmn.log — check for "opmn ready"
10. Repeat steps 2-9 on APP02
```

Backout Steps:
```
1. Stop OC4J on both nodes
2. Restore previous JAR: cp /deploy/backup/XXGE_ASN_v1.1.jar $JAVA_TOP/xxge/XXGE_ASN.jar
3. Start OC4J
```

Estimated Duration: 20 minutes. User Impact: OAF pages unavailable during bounce (rolling bounce minimizes downtime).

**571. How do you deploy concurrent programs in EBS and ensure they work in PROD?**
Deployment steps: (1) **PL/SQL package** — deploy via SQL script: `CREATE OR REPLACE PACKAGE BODY XXGE_CP_PKG...`; grant execute to PUBLIC. (2) **Executable registration** — FNDLOAD: `FNDLOAD APPS/... 0 Y UPLOAD $FND_TOP/patch/115/import/afcpprog.lct XXGE_CP_PROG.ldt`. This registers the executable in `FND_EXECUTABLES`. (3) **Program definition** — FNDLOAD with `afcpprog.lct` for the program definition (`FND_CONCURRENT_PROGRAMS`), parameters (`FND_CONCURRENT_PROGRAM_PARAMETERS`). (4) **Request group assignment** — FNDLOAD with `afcpreqg.lct`. (5) **Validation** — in PROD, navigate to `System Administrator > Concurrent > Programs > Define` and verify the program appears; submit it manually, verify it completes with status `Normal`. Check output/log files via `View Concurrent Requests`.

**572. What documentation standards do you follow for EBS customizations?**
(1) **Technical Design Document (TDD)** — mandatory for all CEMLIs before dev starts. Stored in Confluence. (2) **Inline code comments** — only for non-obvious logic (not for every line). PL/SQL package header comment: package purpose, author, creation date, modification history. (3) **FNDLOAD scripts** — each `.ldt` file has a header comment with CEMLI ID and description. (4) **Deployment runbook** — step-by-step instructions that any developer can follow, not just the author. Include expected output for each step. (5) **Test scripts** — numbered steps with expected vs actual result columns. (6) **CEMLI register** — master spreadsheet with all custom objects cross-referenced to JIRA tickets. (7) **Git commit messages** — `[JIRA-ID] Brief description of change`. (8) **Post-go-live runbook** — support procedures for top issues. All documentation stored in Confluence and linked from JIRA tickets.

**573. How do you store FNDLOAD LCT and LDT files in a Git repository?**
Store in `fndload/` directory organized by object type: `fndload/menus/`, `fndload/responsibilities/`, `fndload/concurrent_programs/`, `fndload/profile_options/`, `fndload/messages/`, `fndload/lookups/`, `fndload/value_sets/`, `fndload/request_groups/`. Each LDT file named by CEMLI ID: `XXGE_ISUP_RESP.ldt`, `XXGE_PROMISE_DATE_MSG.ldt`. The corresponding FNDLOAD download command is documented in a `README.md` in each subdirectory. On deployment, the runbook references the specific LDT files and the correct LCT file from `$FND_TOP/patch/115/import/`. This ensures the Git history shows exactly when and what AOL objects changed — critical for debugging "something changed in PROD that we didn't intend" scenarios.

**574. What are the risks of patching EBS without adequate UAT?**
(1) **CEMLI breakage** — OAF substitutions may fail if patched class signatures changed; PL/SQL packages calling patched standard APIs may get compile errors. (2) **Profile option changes** — patches sometimes add or modify profile option default values, changing system behavior silently. (3) **Data model changes** — patches occasionally add NOT NULL columns to standard tables; custom packages inserting into those tables will error. (4) **Workflow changes** — WF item type changes can break in-flight workflow instances. (5) **Personalization reset** — MDS (JDR) patches can wipe personalizations. (6) **Performance regressions** — new code paths may be slower. Without UAT: you discover these in PROD during business hours. With UAT: you catch them in a controlled environment. Minimum viable UAT for a patch: run the 30 core test scripts + compile XXGE packages after patch and check for errors.

**575. How do you use SQL Developer in your daily EBS development work?**
Daily uses: (1) **Query data** — write and run SQL against EBS tables; use SQL Developer's code completion for table/column names. (2) **Debug PL/SQL** — set breakpoints in packages, step through code with the PL/SQL Debugger (requires `DEBUG CONNECT SESSION` privilege). (3) **Explain Plan** — F10 key shows execution plan inline; switch to Plan tab for graphical plan. (4) **AUTOTRACE** — View > Autotrace — see statistics for any query. (5) **Export results** — export query results to CSV/Excel for data analysis. (6) **Schema browser** — explore table structure, constraints, indexes without writing DDL queries. (7) **Run scripts** — execute `.sql` deployment scripts directly. (8) **DB connections** — maintain connection profiles for DEV/UAT/PROD (with PROD being read-only for safety). Keyboard shortcut: F5 runs the current statement; Ctrl+Enter runs the script.

**576. How do you set up JDeveloper for OAF development?**
Steps: (1) Install JDeveloper 10.1.3.x (must match EBS OAF version — for R12.1.x use 10.1.3.4, for R12.2.x use 10.1.3.5). (2) Copy OAF libraries from EBS application server: `$JAVA_TOP/*.jar`, `$OAF_CLASSPATH jars` to local `jdevlib/` folder. (3) In JDeveloper: Tools > Manage Libraries — add a new library pointing to the copied JARs. (4) Create a new project, add the OAF library. (5) Download the page XML from EBS using `FNDLOAD DOWNLOAD JDR_*` and open in JDeveloper OA Extension. (6) For coding: extend `OAPageLayoutController`, override `processRequest`, import `oracle.apps.fnd.framework.*`. (7) Build and deploy: `ojdeploy` to create JAR; copy to `$JAVA_TOP` on app server. Key: JDeveloper version and EBS OAF version must match exactly, or you get mysterious class compatibility errors at runtime.

**577. How do you use Eclipse or another IDE for the Spring Boot EBS integration service?**
For the Spring Boot REST service (Java, EBS SOAP integration): Eclipse IDE with Spring Tools Suite (STS) plugin. Project setup: Maven or Gradle project; Spring Boot starter dependencies (`spring-boot-starter-web`, `spring-boot-starter-ws` for SOAP, `spring-boot-starter-jdbc` for direct DB access). Local development: point `application.properties` to a local EBS DEV database. Run/debug with embedded Tomcat. Key Eclipse features used: (1) Spring Boot Dashboard — start/stop app with one click. (2) Breakpoints in `@RestController` methods. (3) HTTP client (REST Client plugin) to test endpoints. (4) Maven dependency management — `pom.xml` for adding Oracle JDBC driver. Code review: PRs in GitHub reviewed in browser. Deployments to test server via Jenkins pipeline (Git push → Jenkins build → Docker image → Kubernetes pod or standalone JAR on app server).

**578. What EBS log files do you check when debugging an issue?**
(1) **OAF/OC4J logs** — `$LOG_HOME/ora/10.1.3/j2ee/OC4J_oacore/application.log` — exceptions from OAF controllers and AMs. (2) **Apache/OHS access log** — `$IAS_ORACLE_HOME/Apache/Apache/logs/access_log` — HTTP requests; useful for 404s and timeouts. (3) **FND Concurrent log** — `View Concurrent Requests > View Log` in EBS UI; or directly at `$APPLCSF/$APPLLOG/XXXXXXXX.req` (req file number). (4) **Alert log** — `$ORACLE_BASE/diag/rdbms/.../alert_<SID>.log` — DB-level errors (ORA- messages, startup/shutdown). (5) **FND_LOG_MESSAGES** — for EBS modules with FND logging enabled; query: `SELECT * FROM fnd_log_messages WHERE module LIKE 'pos.%' ORDER BY log_sequence DESC`. (6) **OPMN log** — `$ORACLE_HOME/opmn/logs/ons.log` — OC4J process management. Check #1 first for OAF issues; #3 for CP issues.

**579. What is the ADX utility and when is it used in EBS?**
ADX (Applications DBA) is a menu-driven utility (`adadmin`) for EBS system administration tasks: (1) **Compile APPS schema** — recompile invalid objects (`utlrp` equivalent with EBS awareness). (2) **Recreate grants and synonyms** — required after installing custom objects; ensures `APPS` user can access new tables in custom schemas. (3) **Maintain snapshot information** — tracks installed patches. (4) **Generate forms and reports** — recompile Oracle Forms `.fmx` and Reports `.rdf` files after source changes. (5) **Maintain current view snapshots** — used during patching to maintain `_all` views. Commonly used after: deploying new `XXGE_*` tables (run "Recreate grants/synonyms" so APPS can access them), after patching (run "Compile APPS schema" to catch broken packages), after JDeveloper errors suggest class path issues.

**580. What is the difference between adpatch and ADOP in Oracle EBS?**
**adpatch** (pre-R12.2 / R12.1): traditional patch application tool; requires bringing down all application tier services during patching — downtime window. (2) **ADOP** (AD Online Patching, R12.2+): supports online patching — the system remains available during most of the patch cycle. Uses a dual file system ("run" edition + "patch" edition). ADOP phases: `prepare` (creates patch edition), `apply` (applies patch to patch edition — system runs on run edition), `finalize` (prepares for cutover), `cutover` (switches run edition to patch edition — brief ~5-minute downtime), `cleanup` (removes old run edition). ADOP dramatically reduces patching downtime from 4–8 hours (adpatch) to 10–30 minutes (cutover window only). For GE's quarterly patches, switching to ADOP in R12.2 was a major operational improvement.

**581. What is the APPL_TOP directory and what does it contain?**
`APPL_TOP` is the root directory of the Oracle Applications product file system. Key subdirectories: (1) `$APPL_TOP/APPSORA.env` — environment setup script sourced before any EBS command. (2) `$APPL_TOP/po/12.0.0/` — Oracle Purchasing product home (similar for other products). Within each product home: `bin/` (executables), `forms/US/` (Forms `.fmx`), `reports/US/` (Reports `.rdf`), `sql/` (SQL scripts), `patch/115/import/` (FNDLOAD control files). (3) `$JAVA_TOP` — custom and standard Java classes and JARs. (4) `$OA_HTML` — OAF HTML files, static resources, `.cache/` for OAF page cache. (5) `$COMMON_TOP/admin/scripts/` — admin scripts (`adapcctl.sh`, `adcmctl.sh`). Knowing APPL_TOP structure is essential for deploying OAF JARs, FNDLOAD scripts, and finding log files.

**582. What is a RUP (Release Update Pack) and how does it affect customizations?**
A RUP is a major cumulative patch bundle for EBS (e.g., "HR RUP6"). It applies all patches released for that module since the last RUP. Impact on customizations: (1) Standard packages we referenced may have new signatures or behavior. (2) OAF pages we substituted may have new methods — our substitution class must override the correct new method. (3) Database columns may have been added to standard tables — custom VOs querying `SELECT *` may get unexpected extra columns. (4) BPA/security changes may affect profile options. Pre-RUP protocol: (1) Review RUP readme for "Impact on Customizations" section. (2) Run CEMLI impact analysis. (3) Apply in DEV first, recompile custom packages, check for errors. (4) Test all CEMLIs in the affected module. (5) Document changes needed before UAT.

**583. How do you track the CEMLI inventory and ensure nothing is lost during patching?**
CEMLI register (Excel/Confluence) with: CEMLI ID, Type (OAF/PL/SQL/BIP/WF/FNDLOAD), Object name, Description, Patch risk (standard objects modified?), Last tested date, Last patched version when tested. Before each patch: (1) Query `AD_BUGS` for the patch number — check if any standard objects in our CEMLI dependencies are included. (2) Run `SELECT object_name, status FROM dba_objects WHERE status = 'INVALID' AND owner = 'APPS'` post-patch. (3) Cross-reference invalid objects with CEMLI register. High-patch-risk CEMLIs (those substituting or wrapping standard classes) are always regression-tested. The register is the single source of truth — if a CEMLI isn't in it, it doesn't exist officially and can't be supported.

**584. How do you conduct a code review for an EBS customization?**
Code review checklist: (1) **Standards** — objects named with `XXGE_` prefix; no direct DML on standard Oracle tables. (2) **APIs** — uses standard EBS APIs (`AP_VENDOR_PUB_PKG`, `PO_CHANGE_API_PVT`) not direct inserts. (3) **Error handling** — all PL/SQL exceptions caught; errors logged via `FND_LOG.STRING`, user messages via `FND_MESSAGE`. (4) **Security** — no hard-coded org_id; MOAC context set before multi-org queries. (5) **Performance** — no row-by-row processing for bulk data; bulk collect/FORALL for >100 rows; no `SELECT *`. (6) **Patching safety** — OAF substitution overrides minimal methods; no copies of standard files. (7) **Test coverage** — TDD includes test scenarios for happy path and error path. Review via Git PR with inline comments. Developer must address all comments before merge. Critical issues (security, data corruption risk) are blockers; style issues are suggestions.

**585. How do you estimate effort for OAF development tasks?**
Breakdown by complexity: (1) **Simple config** (hide/show field via personalization): 0.5 days. (2) **VO attribute change** (add column, change WHERE): 1 day. (3) **CO extension** (add validation, field default): 1–2 days. (4) **AM method + PL/SQL** (new business logic): 2–4 days. (5) **New OAF region** (table region with LOV, save): 3–5 days. (6) **New OAF page** (full flow): 7–15 days. (7) **OAF substitution** (replace standard class): 3–5 days dev + 2 days regression. Add: 50% of dev time for unit testing, 30% buffer for environment issues and code review rework, 10% for FNDLOAD/deployment scripts. Validate estimates with a reference task from the same project — "this is similar to XXGE-OAF-005 which took 4 days" calibrates better than abstract points.

**586. How do you handle technical debt in an EBS customization built under time pressure?**
(Already covered in Q516 — see that answer for the full detail on tech-debt management strategy.)

**587. What is your approach to a hotfix / emergency deployment in EBS PROD?**
Emergency deployment protocol: (1) Confirm P1 severity — is the system down or are users blocked from core operations? (2) Fix in DEV within 1 hour; have another developer review the change (even a quick 15-minute peer review). (3) Test in UAT — at minimum, test the specific broken scenario. Skip full regression if time-critical (document the risk). (4) Raise Emergency CTASK in ServiceNow; get fast-track approval from IT manager. (5) Deploy to PROD following runbook steps — DBA and app team on standby. (6) Validate in PROD immediately post-deployment. (7) Notify stakeholders once resolved. (8) Next business day: write incident report, backfill the normal test coverage, and schedule a proper regression test for the affected area. Never skip step 4 even in an emergency — the audit trail protects you and the organization.

**588. How did you document PL/SQL packages in the GE project?**
Package header: brief description, author, creation date, modification log (date, developer, change description). Procedure headers: only if the purpose is non-obvious from the name. No line-by-line comments — code should be self-explanatory via good naming. Exception: document workarounds explicitly — `-- Oracle Bug 12345678: must call COMMIT before querying FND_GLOBAL`. All packages stored in Git under `plsql/<module>/` with the `.pks` (spec) and `.pkb` (body) files separately — allows easy diff of spec changes (which affect calling code) vs body changes (internal). Deployment script: `CREATE OR REPLACE PACKAGE SPEC...` then `CREATE OR REPLACE PACKAGE BODY...`. Package versioning: `G_VERSION CONSTANT VARCHAR2(10) := '2.3.1'` as a package-level constant, readable via `XXGE_PKG.G_VERSION` for quick version check in PROD.

**589. How do you run a JIRA sprint planning session for an EBS sprint?**
Preparation: product owner prioritizes backlog; dev lead estimates story points (or team does planning poker for complex items). Session agenda (2 hours for a 2-week sprint): (1) Review last sprint velocity (baseline for this sprint). (2) PO presents top backlog stories — explains business value and acceptance criteria. (3) Dev lead asks clarifying questions: "Is this a substitution or personalization?" "Does this need a new DB table?" (4) Team estimates points; if gap between dev and PO expectations, negotiate scope. (5) Dev lead commits to achievable scope for the sprint based on capacity (headcount × 5 days × 6 hours/day × 0.7 productivity = available hours). (6) Stories assigned to developers based on module expertise. (7) Sprint goal stated in one sentence: "By end of sprint, suppliers can view and acknowledge POs via iSupplier." Document outcomes in JIRA sprint; share with stakeholders.

**590. How do you communicate blockers to a non-technical project manager?**
(Already covered detail in Q514.) Short answer: use impact–cause–fix–timeline format. Be specific about what you need and by when. Follow up in writing after any verbal conversation. Don't wait until the daily standup if you're blocked — message the PM immediately.

**591. How do you review a technical design presented by a junior developer?**
Structured review approach: (1) **Functional accuracy** — does the design actually address the requirement? Ask the developer to walk through the happy path step by step. (2) **Standard approach** — is there a simpler OOB solution they missed? (3) **Risk assessment** — what breaks if this fails? Is the rollback plan realistic? (4) **Performance** — will this be OK with PROD data volumes? Ask about the expected row count. (5) **Maintainability** — can another developer understand and maintain this in 6 months? (6) Give feedback as questions, not commands: "How would this handle the case where the PO is on hold?" rather than "This doesn't handle holds." Coaching > critiquing. Document agreed changes in the JIRA ticket. Follow up at code review stage to verify the design was implemented as discussed.

**592. What is ADOP and how does it differ from adpatch?**
(Already covered in Q580 — see that answer for the full adpatch vs ADOP comparison.)

**593. Walk through a CEMLI rollback scenario — what happens if a PROD deployment fails halfway?**
Scenario: OAF JAR deployed but the corresponding PL/SQL package wasn't updated due to a script error — the JAR calls a method that doesn't exist in the DB package yet. Result: OAF page throws a Java exception. Rollback procedure: (1) Check CTASK rollback steps (these were written pre-deployment). (2) Stop OC4J on all nodes. (3) Restore previous JAR from backup folder: `cp /deploy/backup/XXGE_ASN_v1.1.jar $JAVA_TOP/xxge/`. (4) Restart OC4J. (5) Verify the previous JAR version is active: check `XXGE_VERSION` function in PROD. (6) Notify stakeholders: "Deployment rolled back due to partial failure; system is on previous version and fully operational." (7) Fix the script failure, re-test in UAT, schedule a new deployment window. Key lesson: always test rollback steps in UAT before PROD — at least once per quarter.

**594. What is your experience with multi-node OAF setup in EBS?**
GE's setup: 2 application server nodes (APP01, APP02) behind an F5 load balancer with sticky sessions (session affinity based on `ICX_SESSION` cookie). Each node runs: OC4J_oacore (OAF), OC4J_forms, Apache/OHS. OAF is stateful — AM passivation writes state to the DB (`JBO_SESSION`), allowing session recovery if one node fails. Configuration points: (1) `$INST_TOP/ora/10.1.3/j2ee/OC4J_oacore/config/data-sources.xml` — DB connection pool config; identical on both nodes. (2) `jbo.pool.maxsize` in `OAApplicationModule.xml` — AM pool size per node. (3) Apache `mod_oc4j` config for load balancing in `oc4j-connectors.xml`. (4) Sticky sessions ensured via F5 cookie persistence — without this, a user's second request goes to a different node and the AM is not found, causing a re-login. Deployment: JAR must be deployed on ALL nodes simultaneously (rolling bounce to minimize downtime).

**595. Why does OC4J bounce and what are common reasons in EBS?**
Common OC4J bounce causes: (1) **Java OutOfMemoryError (OOM)** — heap exhaustion from memory leak (e.g., growing collection in a static variable, unclosed AM pool). Monitor JVM heap via `JVM Diagnostics` in EM or `jstat -gcutil <pid>`. (2) **New JAR deployment** — OAF class loading requires restart for new JARs. (3) **OAF cache corruption** — stale OAF metadata in `.cache/` after JDR personalization update; clear cache + bounce. (4) **EBS patch application** — patches touching Java code require OC4J restart. (5) **OC4J deadlock** — AM pool starvation combined with a long-running transaction can cause deadlock. (6) **OS-level issue** — NFS mount for `$OA_HTML` becoming unavailable. After each unexpected bounce, check `application.log` for the root cause exception before restarting — bouncing without understanding the cause means it will happen again.

**596. How do you load-balance iSupplier across multiple OC4J nodes?**
Load balancing is configured in Apache `mod_oc4j`: `Oc4jMountCopies 2` and `Oc4jMount /OA_HTML ajp13://APP01:12602|ajp13://APP02:12602` — Apache distributes requests round-robin across both nodes. Sticky sessions: configured at the F5 layer using cookie persistence on the `ASESSIONID` cookie (set by OC4J). Without sticky sessions: user's AM state is on APP01, next request goes to APP02 — AM not found — OAF falls back to creating a new AM (performance hit) or throws an error. For high availability: if APP01 goes down, F5 detects via health check, stops routing to APP01, all traffic to APP02. OC4J on APP02 handles the increased load — size the pool at 60% of max to handle failover. During maintenance: drain APP01 connections (set weight=0 in F5) before bounce to avoid mid-session disruptions.

**597. What documentation artifacts would you hand over at the end of an EBS implementation project?**
Handover package: (1) **CEMLI Register** — all custom objects with JIRA links and deployment commands. (2) **Architecture Document** — network diagram, server names, EBS version, module list, integration diagram. (3) **Support Runbook** — top 20 support scenarios with diagnostic SQL and resolution steps. (4) **Test Scripts** — all 30+ UAT test scripts with last-pass evidence. (5) **Deployment Guide** — how to deploy each type of CEMLI (OAF, PL/SQL, BIP, WF, FNDLOAD). (6) **Environment Guide** — how to access DEV/UAT/PROD, key profile options, admin procedures. (7) **Vendor Contacts** — Oracle Support SR process, DBA team contact, network team contact. (8) **Known Issues / Workarounds** — deferred items from Phase 1, known limitations. (9) **Recorded KT Sessions** — video recordings from the 3-day KT. (10) **Git Repository Access** — onboard support team to the Git repo. Handover acknowledged via sign-off from the receiving support manager.

**598. What is your experience with OAF performance in a multi-node EBS setup?**
Key observations from GE's 2-node setup: (1) **AM pool contention** — peak hours (9–11 AM supplier login time) caused AM pool exhaustion on both nodes simultaneously. Fixed by increasing `jbo.pool.maxsize` from 20 to 40 per node. (2) **Session affinity issues** — a misconfigured F5 maintenance window disabled sticky sessions; users experienced AM not found errors. Fixed by restoring sticky session config. (3) **Cache inconsistency** — OAF page cache (`.cache/`) was not shared between nodes (each node has its own cache). After a JDR personalization update, one node still served the old page. Fixed: always clear cache on ALL nodes simultaneously. (4) **JDBC connection pool** — each node maintains its own pool to the DB. A DB failover event caused stale connections on both nodes. Fixed: enable connection validation (`test-connections-on-match`) to purge stale connections automatically.

**599. How do you write effort estimates that account for EBS-specific risks?**
Standard development estimate × EBS complexity multipliers: (1) **Multi-org risk** (+20%) — if the feature touches multiple OUs, MOAC testing adds significant scope. (2) **Patching risk** (+15%) — if the feature touches a module with a quarterly patch due, add buffer for potential post-patch rework. (3) **OAF substitution** (+30% vs CO extension) — substitutions are higher risk, require more regression testing. (4) **New WF item type** (+50% vs WF notification change) — new item types require thorough testing of all activities and timeout transitions. (5) **Data migration** (2× dev estimate for validation and reconciliation) — data migration validation always takes longer than the migration itself. Present estimates in ranges: "3–5 days depending on MOAC complexity" — never a single point for estimates over 3 days. Document assumptions in the JIRA ticket so scope creep is visible when assumptions change.

**600. Describe your overall approach to delivering a complex OAF feature from requirements to PROD.**
End-to-end delivery: (1) **Requirements** — attend functional workshops; document use cases and acceptance criteria in JIRA stories. Ask "what if" questions to surface edge cases early. (2) **Design** — write TDD; get peer review and functional lead sign-off before writing code. (3) **Development** — feature branch in Git; follow CEMLI standards; write PL/SQL unit tests for business logic using utPLSQL. (4) **Code review** — PR against `develop`; address all review comments; merge only after approval. (5) **DEV testing** — run through all test scenarios manually; verify in OAF diagnostics that VO queries are efficient. (6) **UAT deployment** — deploy via runbook; hand test scripts to functional tester. (7) **UAT fixes** — P1/P2 defects fixed same-sprint; P3 deferred. (8) **UAT sign-off** — functional lead signs the UAT evidence form. (9) **PROD deployment** — CTASK in ServiceNow; deploy during change window; validate smoke test. (10) **Post-go-live** — monitor `FND_LOG_MESSAGES` for errors; be available for hypercare support. Each step documented and traceable. This disciplined approach is what makes EBS customizations maintainable and supportable long-term.
"""

with open("/Users/himanshu/Desktop/Job/Job Preparation/Interview_Prep_200_QA.md", "a", encoding="utf-8") as f:
    f.write(content)

print("Section Z appended (Q561-Q600)")
